services:
  frontend:
    build:
      context: ./apps/ui
      target: development
    volumes:
      - ./apps/ui:/app
      - /app/node_modules
    ports:
      - "3001:3001"

  backend:
    build:
      context: ./apps/service
    volumes:
      - ./apps/service:/app
      - ./apps/service/public:/var/www/html
      - ./.data/service-logs:/var/log/apache2
      - /app/vendor
    ports:
      - "8080:80"
