# Build stage targeting development
FROM node:22-alpine as development

WORKDIR /app

# Copy package files
COPY apps/ui/package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY apps/ui .

# Start development server
CMD ["npm", "run", "start"]
